unique_ids:
  forms:
    Form1: P5ZNVYXVIEKWD3VC6MZVIUWQS3H6QPZE
    Restaurant_map: UER4YESSCAIPQOFFAYETLFGBYI7CXBR4
  modules: {}
  server_modules:
    ServerModule1: 6IIPBOZ2BPGU33PT5CA275OHAFWZUWP7
    ServerModule2: BAPKDRC6JAXRAVNBWQVMLPI3P5PMJ55J
  assets:
    standard-page.html: 2RVJDPMFFI3UCWQRKG5Y6Y25J7S54D5F
    theme.css: PLYDHT3SXLT5F4GESXFOG6XYQWBX33T3
